/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Event: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.address <- map["address"]
    self.boucle <- map["boucle"]
    self.descriptionn <- map["descriptionn"]
    self.end <- map["end"]
    self.endDayName <- map["endDayName"]
    self.endTime <- map["endTime"]
    self.id <- map["id"]
    self.location <- map["location"]
    self.selff <- map["selff"]
    self.start <- map["start"]
    self.startDayName <- map["startDayName"]
    self.startTime <- map["startTime"]
    self.title <- map["title"]
  }
}
