/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class ArticleCollection: Object {

  enum Relationships: String {
    case data = "data"
    case pagination = "pagination"
  }

  var data = List<News>()
  @objc dynamic var pagination: Pagination?

}
