/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Event: Object {

  enum Attributes: String {
    case id = "id" /* Primary Key */
    case address = "address"
    case boucle = "boucle"
    case descriptionn = "descriptionn"
    case end = "end"
    case endDayName = "endDayName"
    case endTime = "endTime"
    case location = "location"
    case selff = "selff"
    case start = "start"
    case startDayName = "startDayName"
    case startTime = "startTime"
    case title = "title"
  }

  @objc dynamic var id: String? /* Primary Key */
  @objc dynamic var address: String?
  @objc dynamic var boucle: String?
  @objc dynamic var descriptionn: String?
  @objc dynamic var end: String?
  @objc dynamic var endDayName: String?
  @objc dynamic var endTime: String?
  @objc dynamic var location: String?
  @objc dynamic var selff: String?
  @objc dynamic var start: String?
  @objc dynamic var startDayName: String?
  @objc dynamic var startTime: String?
  @objc dynamic var title: String?

  override static func primaryKey() -> String? {
    return "id"
  }

}
