/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Event: Object {

  enum Attributes: String {
    case id = "id"
    case address = "address"
    case boucle = "boucle"
    case descriptionn = "descriptionn"
    case end = "end"
    case endDayName = "endDayName"
    case endTime = "endTime"
    case location = "location"
    case selff = "selff"
    case start = "start"
    case startDayName = "startDayName"
    case startTime = "startTime"
    case title = "title"
  }

  dynamic var id: String?
  dynamic var address: String?
  dynamic var boucle: String?
  dynamic var descriptionn: String?
  dynamic var end: String?
  dynamic var endDayName: String?
  dynamic var endTime: String?
  dynamic var location: String?
  dynamic var selff: String?
  dynamic var start: String?
  dynamic var startDayName: String?
  dynamic var startTime: String?
  dynamic var title: String?

  override static func primaryKey() -> String? {
    return "id"
  }

}
