/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class News: Object {

  enum Attributes: String {
    case id = "id" /* Primary Key */
    case chapo = "chapo"
    case date = "date"
    case descriptionn = "descriptionn"
    case idRubrique = "idRubrique"
    case logo = "logo"
    case selff = "selff"
    case soustitre = "soustitre"
    case surtitre = "surtitre"
    case texte = "texte"
    case title = "title"
  }

  let id = RealmOptional<Int64>() /* Primary Key */
  @objc dynamic var chapo: String?
  @objc dynamic var date: String?
  @objc dynamic var descriptionn: String?
  let idRubrique = RealmOptional<Int64>()
  @objc dynamic var logo: String?
  @objc dynamic var selff: String?
  @objc dynamic var soustitre: String?
  @objc dynamic var surtitre: String?
  @objc dynamic var texte: String?
  @objc dynamic var title: String?

  override static func primaryKey() -> String? {
    return "id"
  }

}
