/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Pagination: Object {

  enum Attributes: String {
    case next = "next" /* Primary Key */
    case selff = "selff"
    case totalEntries = "totalEntries"
  }

  @objc dynamic var next: String? /* Primary Key */
  @objc dynamic var selff: String?
  let totalEntries = RealmOptional<Int64>()

  override static func primaryKey() -> String? {
    return "next"
  }

}
