/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Pagination: Object {

  enum Attributes: String {
    case next = "next"
    case selff = "selff"
    case totalEntries = "totalEntries"
  }

  dynamic var next: String?
  dynamic var selff: String?
  dynamic var totalEntries: String?

  override static func primaryKey() -> String? {
    return "next"
  }

}
